language: ruby
cache: bundler
sudo: false

#

rvm:
  - &ruby23 2.3.1
  - &ruby22 2.2.4
  - &ruby21 2.1.8
  - &rhead ruby-head

#

matrix:
  fast_finish: true
  allow_failures:
    - rvm: *rhead

#

notifications:
  email:
    recipients:
      - adam@abemedia.co.uk

#

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_KEY
  on:
    tags: true