destination: _site/
url: "http://127.0.0.1:4007"
baseurl: ""
port: 4007
output: pdf
product: TeamForge
print_title: TeamForge
print_subtitle: 22.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true